//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmsManage.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangPhim
    {
        public DangPhim()
        {
            this.Gias = new HashSet<Gia>();
            this.Phims = new HashSet<Phim>();
        }
    
        public int MaDangPhim { get; set; }
        public string TenDangPhim { get; set; }
    
        public virtual ICollection<Gia> Gias { get; set; }
        public virtual ICollection<Phim> Phims { get; set; }
    }
}
