//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmsManage.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachDatVeOnline
    {
        public int MaDatVe { get; set; }
        public int MaKhachHang { get; set; }
        public int MaXacNhan { get; set; }
        public int MaPhim { get; set; }
        public int SoLuongVeThuong { get; set; }
        public int SoLuongVeVip { get; set; }
        public string TrangThaiDatVe { get; set; }
        public int MaXuatChieu { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual Phim Phim { get; set; }
        public virtual XuatChieu XuatChieu { get; set; }
    }
}
