//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmsManage.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ghe
    {
        public Ghe()
        {
            this.Ves = new HashSet<Ve>();
        }
    
        public int SoGhe { get; set; }
        public int MaPhong { get; set; }
        public bool TrangThaiGhe { get; set; }
        public int MaTinhTrang { get; set; }
        public int MaLoaiGhe { get; set; }
    
        public virtual LoaiGhe LoaiGhe { get; set; }
        public virtual PhongChieu PhongChieu { get; set; }
        public virtual TinhTrang TinhTrang { get; set; }
        public virtual ICollection<Ve> Ves { get; set; }
    }
}
