//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmsManage.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gia
    {
        public int MaGia { get; set; }
        public decimal SoTien { get; set; }
        public int MaDangPhim { get; set; }
        public int MaVe { get; set; }
        public int IdLoaiGhe { get; set; }
    
        public virtual DangPhim DangPhim { get; set; }
        public virtual LoaiGhe LoaiGhe { get; set; }
    }
}
