//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmsManage.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public KhachHang()
        {
            this.DanhSachDatVeOnlines = new HashSet<DanhSachDatVeOnline>();
        }
    
        public int MaKhachHang { get; set; }
        public string TenDangNhap { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
        public bool GioiTinh { get; set; }
        public string MatKhau { get; set; }
    
        public virtual ICollection<DanhSachDatVeOnline> DanhSachDatVeOnlines { get; set; }
    }
}
