//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmsManage.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiGhe
    {
        public LoaiGhe()
        {
            this.Ghes = new HashSet<Ghe>();
            this.Gias = new HashSet<Gia>();
        }
    
        public int MaLoaiGhe { get; set; }
        public string TenLoaiGhe { get; set; }
    
        public virtual ICollection<Ghe> Ghes { get; set; }
        public virtual ICollection<Gia> Gias { get; set; }
    }
}
