//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmsManage.DTO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FilmsManage_DbEntities : DbContext
    {
        public FilmsManage_DbEntities()
            : base("name=FilmsManage_DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DangPhim> DangPhims { get; set; }
        public DbSet<DanhSachDatVeOnline> DanhSachDatVeOnlines { get; set; }
        public DbSet<Ghe> Ghes { get; set; }
        public DbSet<Gia> Gias { get; set; }
        public DbSet<KhachHang> KhachHangs { get; set; }
        public DbSet<LoaiGhe> LoaiGhes { get; set; }
        public DbSet<LoaiPhim> LoaiPhims { get; set; }
        public DbSet<NhanVien> NhanViens { get; set; }
        public DbSet<Phim> Phims { get; set; }
        public DbSet<PhongChieu> PhongChieux { get; set; }
        public DbSet<QuocGia> QuocGias { get; set; }
        public DbSet<Quyen> Quyens { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TinhTrang> TinhTrangs { get; set; }
        public DbSet<Ve> Ves { get; set; }
        public DbSet<XuatChieu> XuatChieux { get; set; }
    }
}
