//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmsManage.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phim
    {
        public Phim()
        {
            this.DanhSachDatVeOnlines = new HashSet<DanhSachDatVeOnline>();
        }
    
        public int MaPhim { get; set; }
        public string GhiChu { get; set; }
        public int DoDaiGio { get; set; }
        public int DoDaiPhut { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public string AnhDaiDien { get; set; }
        public string MoTaPhim { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public int MaLoaiPhim { get; set; }
        public int MaDangPhim { get; set; }
        public int MaXuatChieu { get; set; }
        public string NoiDungPhim { get; set; }
        public int DoTuoi { get; set; }
        public int IdQuocGia { get; set; }
    
        public virtual DangPhim DangPhim { get; set; }
        public virtual ICollection<DanhSachDatVeOnline> DanhSachDatVeOnlines { get; set; }
        public virtual LoaiPhim LoaiPhim { get; set; }
        public virtual QuocGia QuocGia { get; set; }
        public virtual XuatChieu XuatChieu { get; set; }
    }
}
