//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmsManage.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongChieu
    {
        public PhongChieu()
        {
            this.Ghes = new HashSet<Ghe>();
            this.Ves = new HashSet<Ve>();
            this.XuatChieux = new HashSet<XuatChieu>();
        }
    
        public int IdPhongChieu { get; set; }
        public string TenPhongChieu { get; set; }
    
        public virtual ICollection<Ghe> Ghes { get; set; }
        public virtual ICollection<Ve> Ves { get; set; }
        public virtual ICollection<XuatChieu> XuatChieux { get; set; }
    }
}
