//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmsManage.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuocGia
    {
        public QuocGia()
        {
            this.Phims = new HashSet<Phim>();
        }
    
        public int IdQuocGia { get; set; }
        public string TenNuoc { get; set; }
    
        public virtual ICollection<Phim> Phims { get; set; }
    }
}
