//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmsManage.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinhTrang
    {
        public TinhTrang()
        {
            this.Ghes = new HashSet<Ghe>();
        }
    
        public int MaTinhTrang { get; set; }
        public string TenTinhTrang { get; set; }
    
        public virtual ICollection<Ghe> Ghes { get; set; }
    }
}
