//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmsManage.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ve
    {
        public int IdVe { get; set; }
        public int MaPhong { get; set; }
        public int MaGia { get; set; }
        public decimal DonGia { get; set; }
        public int MaXuatChieu { get; set; }
        public int IdNhanVien { get; set; }
        public int SoGhe { get; set; }
        public int MaLichChieu { get; set; }
    
        public virtual Ghe Ghe { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual PhongChieu PhongChieu { get; set; }
        public virtual XuatChieu XuatChieu { get; set; }
    }
}
