//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmsManage.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class XuatChieu
    {
        public XuatChieu()
        {
            this.DanhSachDatVeOnlines = new HashSet<DanhSachDatVeOnline>();
            this.Phims = new HashSet<Phim>();
            this.Ves = new HashSet<Ve>();
        }
    
        public int MaXuatChieu { get; set; }
        public int MaPhim { get; set; }
        public int GioChieu { get; set; }
        public int PhutChieu { get; set; }
        public int IdPhongChieu { get; set; }
    
        public virtual ICollection<DanhSachDatVeOnline> DanhSachDatVeOnlines { get; set; }
        public virtual ICollection<Phim> Phims { get; set; }
        public virtual PhongChieu PhongChieu { get; set; }
        public virtual ICollection<Ve> Ves { get; set; }
    }
}
